CREATE OR REPLACE FUNCTION FN_GET_DEPT_NAME(P_DEPTNO IN NUMBER)
RETURN VARCHAR2
IS
    V_DEPTNAME DEPT.DNAME%TYPE;
BEGIN
    SELECT DNAME INTO V_DEPTNAME
    FROM DEPT
    WHERE DEPTNO=P_DEPTNO;
END;
