/* CREATE TABLE TABLE_NAME(
        COLUMN_NAME DATA_TYPE(LENGTH) ,
        ......
    );
*/ 
DROP TABLE EMP_DDL;
CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COM NUMBER(7,2),
    DEPTNO NUMBER(2)
);
DESC EMP_DDL;
DROP TABLE DEPT_DDL;
CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;
DESC DEPT_DDL;
CREATE TABLE SALGRADE_DDL
AS SELECT * FROM SALGRADE;
DESC SALGRADE_DDL;

/* ALTER TABLE <TABLE_NAME>
    1.ADD <COLNAME> <DATATYPE>;
    2.DROP <COLNAME>;
    3.MODIFY <COLNAME> <DATATYPE>;
    4.RENAME COLUMN <OLD_COLNAME> TO <NEW_COLNAME>
*/
ALTER TABLE SALGRADE_DDL
ADD PARTY VARCHAR2(20);

ALTER TABLE SALGRADE_DDL
RENAME COLUMN PARTY TO HOME;

ALTER TABLE SALGARDE_DDL
MODIFY HOME NUMBER(10);
DESC SALGRADE_DDL;

ALTER TABLE SALGRADE_DDL
DROP COLUMN HOME;

RENAME SALGRADE_DDL TO SALZIP;

DESC SALZIP;
SELECT * FROM SALZIP;

TRUNCATE TABLE SALZIP;
DROP TABLE SALZIP;
/*
COMMENT ON TABLE <TABLE_NAME> IS <COMMENT>;
COMMENT ON COLUMN <TABLE_NAME>.<COLNAME> IS <COMMENT>;
*/
COMMENT ON TABLE DEPT_DDL IS 'DDL연습테이블';
COMMENT ON COLUMN DEPF_DDL.LOC IS '부서위치';

SELECT * FROM USER_TAB_COMMENTS;
SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME='DEPT_DDL';




